trigger:
  branches:
    include:
      - development
  paths:
    include:
      - implementations/landing-page

pr: none

resources:
- repo: self

variables:
  # Set demo global version - manually
  major: 0
  minor: 1
  # Docker Buildkit improves image build performance
  DOCKER_BUILDKIT: 1
  # Image repository
  landingRepo: 'demo-landing'
  landingRepoEndpoint: 'k8scrvidchaindev.azurecr.io/demo-landing'
  # Dockerfiles
  landingDocker: 'implementations/landing-page/Dockerfile'
  # Kubernetes YAML
  landingKubernetes: 'implementations/landing-page/k8s/k8s-dev.yml'
  # Kubernetes namespace
  namespace: 'development'
  # Image tagging: application version - build
  tagLanding: '$(Build.BuildNumber)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: GetShortCommit
    displayName: 'retrieve commit hash'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        commit=$(Build.SourceVersion)
        shortCommit=${commit:0:7}
        echo "##vso[build.updatebuildnumber]$(major).$(minor).$(Build.BuildId)-commit.$shortCommit"
      displayName: 'retrieve $(packageJson) version'
  - job: BuildLandingDemo
    displayName: 'Build Landing demo'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - script: "docker pull $(landingRepoEndpoint):latest"
      displayName: Pull latest for layer caching
      continueOnError: true # for first build, no cache
    - task: Docker@2
      displayName: "build --cache-from=$(landingRepoEndpoint):latest"
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(landingRepo)'
        command: 'build'
        Dockerfile: $(landingDocker)
        arguments: '--cache-from=$(landingRepoEndpoint):latest' 
        tags: |
          $(tagLanding)
          latest
    - task: Docker@2
      displayName: "push"
      inputs:
        command: push
        containerRegistry: "$(dockerRegistryServiceConnection)"
        repository: $(landingRepo) 
        tags: |
          $(tagLanding)
          latest
- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: DeployLanding
    displayName: 'Deploy Landing'
    pool:
      vmImage: $(vmImageName)
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: KubernetesManifest@0
            displayName: Create/update deployment
            inputs:              
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: $(landingKubernetes)
              containers: |
                $(landingRepoEndpoint):$(tagLanding)
