trigger:
  branches:
    include:
      - development
  paths:
    include:
      - implementations/vidchain-government/vidchain-government-backend

pr: none

resources:
- repo: self

variables:
  # Docker Buildkit improves image build performance
  DOCKER_BUILDKIT: 1
  # Image repository
  governmentBackendRepo: 'government-backend'
  governmentBackendRepoEndpoint: 'k8scrvidchaindev.azurecr.io/government-backend'
  # Dockerfiles
  governmentBackendDocker: 'implementations/vidchain-government/vidchain-government-backend/Dockerfile'
  # Kubernetes YAML
  governmentBackendKubernetes: 'implementations/vidchain-government/vidchain-government-backend/k8s/k8s-dev.yml'
  # Configmaps
  governmentBackendConfigMap: 'implementations/vidchain-government/vidchain-government-backend/k8s/configmap-dev.yml'
  # Kubernetes namespace
  namespace: 'development'
  # Image tagging: application version - build
  tagGovernmentBackend: '$(Build.BuildNumber)'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: GetShortCommit
    displayName: 'retrieve commit hash'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        commit=$(Build.SourceVersion)
        shortCommit=${commit:0:7}
        echo "##vso[build.updatebuildnumber]$(Build.BuildId)-commit.$shortCommit"
      displayName: 'retrieve $(packageJson) version'
  - job: BuildGovernmentBackend
    displayName: 'Build Government Backend'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - script: "docker pull $(governmentBackendRepoEndpoint):latest"
      displayName: Pull latest for layer caching
      continueOnError: true # for first build, no cache
    - task: Docker@2
      displayName: "build --cache-from=$(governmentBackendRepoEndpoint):latest"
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(governmentBackendRepo)'
        command: 'build'
        Dockerfile: $(governmentBackendDocker)
        arguments: '--cache-from=$(governmentBackendRepoEndpoint):latest' 
        tags: |
          $(tagGovernmentBackend)
          latest
    - task: Docker@2
      displayName: "push"
      inputs:
        command: push
        containerRegistry: "$(dockerRegistryServiceConnection)"
        repository: $(governmentBackendRepo) 
        tags: |
          $(tagGovernmentBackend)
          latest
- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: DeployGovernmentBackend
    displayName: 'Deploy Government Backend'
    pool:
      vmImage: $(vmImageName)
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Kubernetes@1
            displayName: Create/update configmap
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(governmentBackendConfigMap) -n $(namespace)
          - task: KubernetesManifest@0
            displayName: Create/update deployment
            inputs:              
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: $(namespace)
              manifests: $(governmentBackendKubernetes)
              containers: |
                $(governmentBackendRepoEndpoint):$(tagGovernmentBackend)