# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- ci/cd-azure-pipeline-aks

resources:
- repo: self

variables:

  governmentBackendRepo: 'government-backend'
  governmentBackendDocker: 'implementations/vidchain-government/vidchain-government-backend/Dockerfile'
  governmentBackendKubernetes: 'implementations/vidchain-government/vidchain-government-backend/k8s.yaml'
  governmentFrontendRepo: 'government-frontend'
  governmentFrontendDocker: 'implementations/vidchain-government/vidchain-government-frontend/Dockerfile'
  governmentFrontendKubernetes: 'implementations/vidchain-government/vidchain-government-frontend/k8s.yaml'
  universityBackendRepo: 'university-backend'
  universityBackendDocker: 'implementations/vidchain-university/vidchain-university-backend/Dockerfile'
  universityBackendKubernetes: 'implementations/vidchain-university/vidchain-university-backend/k8s.yaml'
  universityFrontendRepo: 'university-frontend'
  universityFrontendDocker: 'implementations/vidchain-university/vidchain-university-frontend/Dockerfile'
  universityFrontendKubernetes: 'implementations/vidchain-university/vidchain-university-frontend/k8s.yaml'
  landingRepo: 'demo-landing'
  landingDocker: 'implementations/landing-page/Dockerfile'
  landingKubernetes: 'implementations/landing-page/k8s.yaml'
  namespace: 'development'

  #tag: '$(Build.BuildId)'
  tag: 'latest'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  
stages:
- stage: Build
  displayName: 'Build stage'
  jobs:  
  - job: BuildGovernmentBackend
    displayName: 'Build Government Backend'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push Government Backend image to container registry
      inputs:
        command: buildAndPush
        repository: $(governmentBackendRepo)
        dockerfile: $(governmentBackendDocker)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
  - job: BuildGovernmentFrontend
    displayName: 'Build Government Frontend'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an Government Frontend image to container registry
      inputs:
        command: buildAndPush
        repository: $(governmentFrontendRepo)
        dockerfile: $(governmentBackendDocker)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
  - job: BuildUniversityBackend
    displayName: 'Build University Backend'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push University Backend image to container registry
      inputs:
        command: buildAndPush
        repository: $(universityBackendRepo)
        dockerfile: $(governmentBackendDocker)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
  - job: BuildUniversityFrontend
    displayName: 'Build University Frontend'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an University Frontend image to container registry
      inputs:
        command: buildAndPush
        repository: $(universityFrontendRepo)
        dockerfile: $(universityFrontendDocker)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
  - job: BuildLandingDemo
    displayName: 'Build Landing demo'
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an Landing demo image to container registry
      inputs:
        command: buildAndPush
        repository: $(landingRepo)
        dockerfile: $(landingDocker)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Deploy
  displayName: 'Deploy stage'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Deploy'
    pool:
      vmImage: $(vmImageName)
    environment: 'development'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Kubernetes@1
            displayName: kubectl apply for Government Backend
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(System.DefaultWorkingDirectory)/$(governmentBackendKubernetes) -n $(namespace)
          - task: Kubernetes@1
            displayName: kubectl apply for Government Frontend
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(System.DefaultWorkingDirectory)/$(governmentFrontendKubernetes) -n $(namespace)
          - task: Kubernetes@1
            displayName: kubectl apply for University Backend
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(System.DefaultWorkingDirectory)/$(universityBackendKubernetes) -n $(namespace)
          - task: Kubernetes@1
            displayName: kubectl apply for University Frontend
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(System.DefaultWorkingDirectory)/$(universityFrontendKubernetes) -n $(namespace)
          - task: Kubernetes@1
            displayName: kubectl apply for Landing demo
            inputs:
              connectionType: Azure Resource Manager
              azureSubscriptionEndpoint: $(azureSubscriptionEndpoint) 
              azureResourceGroup: $(azureResourceGroup)
              kubernetesCluster: $(kubernetesCluster)
              command: apply
              arguments: -f $(System.DefaultWorkingDirectory)/$(landingKubernetes) -n $(namespace)