apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-landing-deployment
  labels:
    app: demo-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-landing
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: demo-landing
    spec:
      containers:
      - image: k8scrvidchaindev.azurecr.io/demo-landing:v0.5
        imagePullPolicy: "Always"
        name: demo-landing
        ports:
        - containerPort: 3028
        env:
        - name: PUBLIC_URL
          value: https://dev.vidchain.net/demo
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: demo-landing-service
  labels:
    app: demo-landing
spec:
  type: ClusterIP
  ports:
  - name: "3028"
    port: 3028
  selector:
    app: demo-landing

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-landing-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /demo/$2
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - dev.vidchain.net
    secretName: tls-secret
  rules:
  - host: dev.vidchain.net
    http:
      paths: 
      - path: /demo(/|$)(.*)
        backend:
          serviceName: demo-landing-service
          servicePort: 3028
        
