version: "3.7"

services:

  government-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vidchain/ government-frontend:v0.1
    container_name:  government-frontend
    restart: always
    logging:
      options:
        max-size: "100m"
        max-file: "50"
    ports:
      - 3022:3022
    networks:
      - hydra_network
    environment:
      - REDIS_URL=redis
      - REACT_APP_BACKEND_URL=http://localhost:3021
      - REDIRECT_CALLBACK=http%3A%2F%2F127.0.0.1%3A3022%2Fcallback
      
networks:
  hydra_network:
    driver: bridge
    name: hydra_oidc_network