version: "3.7"

services:

  government-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vidchain/government-frontend:v0.1
    container_name:  government-frontend
    networks:
      - hydra_network
    ports:
      - 3022:3022
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - REDIRECT_CALLBACK=https://dev.api.vidchain.net/demo/callback
      - IDENTITY_PROVIDER=https://dev.api.vidchain.net
      - PUBLIC_URL=https://dev.api.vidchain.net/demo
networks:
  hydra_network:
    driver: bridge
    name: hydra_oidc_network
      