apiVersion: apps/v1
kind: Deployment
metadata:
  name: government-frontend-deployment
  labels:
    app: government-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: government-frontend
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: government-frontend
    spec:
      containers:
      - image: k8scrvidchaindev.azurecr.io/government-frontend:v0.1-build.30
        imagePullPolicy: "Always"
        name: government-frontend
        ports:
        - containerPort: 3022
        env:
        - name: REACT_APP_REDIRECT_CALLBACK
          valueFrom:
            configMapKeyRef:
              name: government-frontend-configmap
              key: REACT_APP_REDIRECT_CALLBACK
        - name: REACT_APP_IDENTITY_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: government-frontend-configmap
              key: REACT_APP_IDENTITY_PROVIDER
        - name: REACT_APP_DEMO
          valueFrom:
            configMapKeyRef:
              name: government-frontend-configmap
              key: REACT_APP_DEMO
        - name: REACT_APP_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: government-frontend-configmap
              key: REACT_APP_BACKEND_URL
        - name: REACT_APP_WS_URL
          valueFrom:
            configMapKeyRef:
              name: government-frontend-configmap
              key: REACT_APP_WS_URL
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: government-frontend-configmap
              key: PUBLIC_URL
        - name: REACT_APP_API_KEY
          valueFrom:
            secretKeyRef:
              name: government-api-key
              key: api-key
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: government-frontend-service
  labels:
    app: government-frontend
spec:
  type: ClusterIP
  ports:
  - name: "3022"
    port: 3022
  selector:
    app: government-frontend

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: government-frontend-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /demo/government/$2
spec:
  tls:
  - hosts:
    - try.vidchain.net
    secretName: tls-secret-production
  rules:
  - host: try.vidchain.net
    http:
      paths: 
      - path: /demo/government(/|$)(.*)
        backend:
          serviceName: government-frontend-service
          servicePort: 3022