apiVersion: apps/v1
kind: Deployment
metadata:
  name: government-backend-deployment
  labels:
    app: government-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: government-backend
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: government-backend
    spec:
      containers:
      - image: k8scrvidchaindev.azurecr.io/government-backend:v0.4
        imagePullPolicy: "Always"
        name: government-backend
        ports:
        - containerPort: 3021
        env:
        - name: BASE_URL
          value: https://dev.vidchain.net/demo/governmentbackend
        - name: PORT
          value: "3021"
        - name: REDIS_URL
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: WS_URL
          value: https://dev.vidchain.net
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: government-api-key
              key: api-key
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: government-backend-service
  labels:
    app: government-backend
spec:
  type: ClusterIP
  ports:
  - name: "3021"
    port: 3021
  selector:
    app: government-backend

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: government-backend-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - dev.vidchain.net
    secretName: tls-secret
  rules:
  - host: dev.vidchain.net
    http:
      paths:
      - path: /demo/governmentbackend
        backend:
          serviceName: government-backend-service
          servicePort: 3021
      - path: /governmentws
        backend:
          serviceName: government-backend-service
          servicePort: 3021
