version: "3.7"
services:
  university-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vidchain/university-backend:v0.1
    container_name:  university-backend
    ports:
      - 3021:3021