version: "3.7"
services:
  university-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vidchain/university-backend:v0.1
    container_name:  university-backend
    ports:
      - 3023:3023
    environment:
      - BASE_URL=https://dev.api.vidchain.net/universitybackenddemo
      - PORT=3023