name: WIP - Deploy development university demo on AKS

on:
  push:
    branches:
      - ci/cd-github-actions-aks

env:
  CLUSTER_NAME: k8s-vidchain-dev
  CLUSTER_RESOURCE_GROUP: rg-vidchain-dev
  NAMESPACE: development
  FRONTEND_IMAGE_NAME: vidchain-university-frontend
  BACKEND_IMAGE_NAME: vidchain-university-backend

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Get code from the repo"
        uses: actions/checkout@v2
        with:
          ref: ci/cd-github-actions-aks
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        run: |          
          docker build . --file ./vidchain-university-frontend/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.FRONTEND_IMAGE_NAME}}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.FRONTEND_IMAGE_NAME}}:${{ github.sha }}
          docker build . --file ./vidchain-university-backend/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.BACKEND_IMAGE_NAME}}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{env.BACKEND_IMAGE_NAME}}:${{ github.sha }}

  deploy-to-aks:
    needs: [build-and-push-docker-image]
    runs-on: ubuntu-latest
    steps:
      - name: "Get code from the repo"
        uses: actions/checkout@v2
        with:
          ref: ci/cd-github-actions-aks
      - name: "Set the context"
        uses: azure/aks-set-context@v1
        with:
          creds: "${{secrets.AZURE_CREDS_AKS_SCOPE}}"
          cluster-name: ${{env.CLUSTER_NAME}}
          resource-group: ${{env.CLUSTER_RESOURCE_GROUP}}
      - name: "Create imagePullSecret for Azure Container Registry"
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER}}
          container-registry-username: ${{secrets.REGISTRY_USERNAME}}
          container-registry-password: ${{secrets.REGISTRY_PASSWORD}}
          secret-name: acr-connection
          namespace: ${{env.NAMESPACE}}
      - name: "Frontend deployment"
        id: deployment
        uses: azure/k8s-deploy@v1
        with:
          manifests: ./vidchain-university-frontend/k8s.yaml
          images: ${{secrets.REGISTRY_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:${{github.sha}}
          imagepullsecrets: acr-connection
          namespace: ${{env.NAMESPACE}}
      - name: "Backend deployment"
        id: deployment
        uses: azure/k8s-deploy@v1
        with:
          manifests: ./vidchain-university-backend/k8s.yaml
          images: ${{secrets.REGISTRY_LOGIN_SERVER}}/${{env.IMAGE_NAME}}:${{github.sha}}
          imagepullsecrets: acr-connection
          namespace: ${{env.NAMESPACE}}